extends Node
# A biblioteca imortal de Filipin
var poemas: Array = [
	"POEMA 01 - O início de uma desventura épica\n\nFilipin era um garoto muito engraçado, ele gostava de peças e maquinário\nMexer no celular e comer miojo era sua paixão, e no ramo dos perfumes era mercenário\nSobrevive através de mitose, se duplica e que sobrevivam os melhores\nSeu cabelo sempre esbelto, o ambiente reflete os sorrisos que colores\n\nDe fio em fio, de leite em leite, Fillipin faz seu legado\nNão come muito, mas gosta de tomar muito achocolatado\nNão gostava de estudar, principalmente física e matemática\nSe os professores os confrontavam, na sua mente só vinha estática\n\nMenino arrojado irreverente\nJá não acredita mais na fada do dente\nMas esperança é algo que não lhe falta\nPois passar de ano é algo que ele exalta\n\nEntretanto, estudar não é seu forte\nJá que mesmo com alguém lhe dando um norte\nSem trapacear sua nota cai em decadência\n\nNão o entenda mal\nSeu aspecto é existencial\nMesmo que com isso ele não perca a excelência.",
	
	"POEMA 02 - Desembainhando a lapiseira\n\nA jornada começa\nSem prosa nem pressa\nDificuldades aparecerão\nE Fillipin as vencerá com lápis na mão\n\nCom seu miojo ao lado\nQualquer coisa é um barato\n\nSem estudar\nSem pestanejar\nSem dromedários para incomodar\nDo mau ganhará\n\nLutando contra professores e bebedouro\nSua aventura será um estouro\n\nPerfumes estarão a esperar\nSe inimigos ele finalizar\nCom pouco cabelo\nE emoção\nO final exige interpretação",
	
	"POEMA 03 - Bamor\n\nA futilidade da amizade\nNão ausenta sua ânsia por fraternidade\nPois nunca deixará de amar uma menina\nMesmo que nela pouco tenha dado em cima\n\nNos corredores cheios do colégio\nOnde o tempo parece não passar\nEle busca o doce privilégio\nDe ver sua musa enfim o iluminar\n\nEntre cadernos, livros e o sinal\nSeu olhar tem destino compassado\nUma menina loira, sem igual\nQue o deixa completamente mudo e fascinado\n\nMesmo que o futuro dos dois seja incerto\nFillipin não deixará de desejá-la\nPorque o amor, mesmo reprimido, fala\nE sua paixão o manterá desperto",
	
	"POEMA 04 - Teléfono\n\nMaldito governo\nNão me deixa pegar meu celular\nFaz da minha aula um inferno\nNão me deixam jogar minha Briga Estrelar\n\nÉ difícil sem meu celulárico\nFico sem opções alternativas\nE tenho de empenhar esforço homérico\nA fim de ter soluções definitivas\n\nRodar de ano eu tenho medo\nMas do professor não\nPois pra ganhar eu mudo até o enredo\nE faço meu adversário de bobão\n\nMeus poder é eterno\nImutável e perene\nA menos que chegue o inverno\nQue me derrota de forma solene",
	
	"POEMA 05 - O cume de Fillipin\n\nNo alto daquele cume\nUm homem no cume vejo\nEle irradia seu semblante\nSempre de maneira extravagante\n\nUm homem musculoso e belo\nRefletindo o sol amarelo\nDiante da escuridão, ele me estendeu a mão\nSeria sonho, ou um delírio da paixão?\n\nDe passo em passo, de pedal em pedal\nNossa relação crescia maior que a de um casal\nCada caminhada um desafio diferente\nMas com ele ao meu lado, não temia o que viria a frente\n\nDiante de todo o caos, de todo o horror\nVeio aquele homem, com o seu esplendor\nMuitos enxergam na luz a esperança como um acepipe\nMas para mim, a esperança, se chama Felipe",
	
	"POEMA 06 - Inus Phiillipinus\n\nSactifitrorum miojus nostrus\nAlimentiforum toddynhus sacrus\nnunquam estudum in aulum\nnunquam acendus a lux\nVade retro livroum\n\nLorem sapium lindus cabbelum\nNarigus supremmus ardentus\nMatematicus naum gostum\nIpse semprus erectus\n\nUtilitus telefonus mium\nbrawlus starus sempru jogarus\nno comerum aluminium\nPotens austrus Phillipinus",
	
	"POEMA 07 - Alhamfllipilila\n\nFi qadeem el-zaman, kana honaka fares\nshoja' wa moghamre nabil yod'a Fillipin.\n\nLam yakon yabhath 'an el-dhahab aw el-jah,\nbal kana yatof el-'alam bahithan 'an el-haq\nwa mosa'adat el-do'afa'a. Kana\nFillipin yamtalik qalban naqeyan kal-thalj,\nwa shoja'ah tahaboha el-wohoosh wal-zalemoon.",
	
	"POEMA 08 - Idas e vindas\n\nLápis, espada\nCapa, armadura\nPalavras, tiros\nLivros, bacamartes\n\nMiojo, alimento\nToddynho, salvação\nOsmose, transcendência\nEduardo, perdição\n\nMesmo quando se perde\nSe encontra no fim\nSem ainda estar afim\nAcham o amarelo no meio do verde\n\nPor mais que a passagem seja derradeira\nTal rumada ainda não é a verdadeira\nPois o complementar sempre te aguarda\npara que você mate o salvaguarda"
]
